const SILOS_LOAD_START = 'SILOS_LOAD_START';
const SILOS_LOAD_SUCCESS = 'SILOS_LOAD_SUCCESS';
const SILOS_LOAD_ERROR = 'SILOS_LOAD_ERROR';

const AUTH_START = 'AUTH_START';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

const MEASUREMENTS_START = 'MEASUREMENTS_START';
const MEASUREMENTS_SUCCESS = 'MEASUREMENTS_SUCCESS';
const MEASUREMENTS_ERROR = 'MEASUREMENTS_ERROR';

const GRAPH_MEASUREMENTS_START = 'GRAPH_MEASUREMENTS_START';
const GRAPH_MEASUREMENTS_SUCCESS = 'GRAPH_MEASUREMENTS_SUCCESS';
const GRAPH_MEASUREMENTS_ERROR = 'GRAPH_MEASUREMENTS_ERROR';

const SET_USERNAME = 'SET_USERNAME';

const LOGOUT_USER = 'LOGOUT_USER';

const NOTIFICATIONS_LOAD_ERROR = 'NOTIFICATIONS_LOAD_ERROR';
const NOTIFICATIONS_LOAD_START = 'NOTIFICATIONS_LOAD_START';
const NOTIFICATIONS_LOAD_SUCCESS = 'NOTIFICATIONS_LOAD_SUCCESS';

const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export {
  SILOS_LOAD_START,
  SILOS_LOAD_SUCCESS,
  SILOS_LOAD_ERROR,
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_ERROR,
  MEASUREMENTS_START,
  MEASUREMENTS_SUCCESS,
  MEASUREMENTS_ERROR,
  GRAPH_MEASUREMENTS_START,
  GRAPH_MEASUREMENTS_SUCCESS,
  GRAPH_MEASUREMENTS_ERROR,
  SET_USERNAME,
  LOGOUT_USER,
  NOTIFICATIONS_LOAD_ERROR,
  NOTIFICATIONS_LOAD_SUCCESS,
  NOTIFICATIONS_LOAD_START,
  CHANGE_LANGUAGE,
};
