const STATUS_LOAD_START = 'STATUS_LOAD_START';
const STATUS_LOAD_SUCCESS = 'STATUS_LOAD_SUCCESS';
const STATUS_LOAD_ERROR = 'STATUS_LOAD_ERROR';

const AUTH_START = 'AUTH_START';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

export {
  STATUS_LOAD_START,
  STATUS_LOAD_SUCCESS,
  STATUS_LOAD_ERROR,
  AUTH_START,
  AUTH_SUCCESS,
  AUTH_ERROR,
};
