const STATUS_LOAD_START = 'STATUS_LOAD_START';
const STATUS_LOAD_SUCCESS = 'STATUS_LOAD_SUCCESS';
const STATUS_LOAD_ERROR = 'STATUS_LOAD_ERROR';

export {
  STATUS_LOAD_START,
  STATUS_LOAD_SUCCESS,
  STATUS_LOAD_ERROR,
};
